<?php if (count($this->getLoadedProductCollection())): ?>
    <div class="cb-recently-view">
        <h6><?php echo $this->__('Product Near By You'); ?></h6>
        <div class="side-content-view">
            <a class="" href="<?php echo $this->getUrl('productbyzipcode/search/product'); ?>"><?php echo $this->__('View all'); ?></a>
        </div>
        <div id="owl-demo" class="owl-carousel owl-theme">
            <?php foreach ($this->getLoadedProductCollection() as $_link): ?>
                <div class="item">
                    <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(150) ?>" alt="<?php echo $this->escapeHtml($_link->getName()) ?>" />
                    </a>
                    <div class="product-info">
                        <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>"><?php echo $this->escapeHtml($_link->getName()) ?></a></h3>
                        <?php echo $this->getPriceHtml($_link, true) ?>
                        <?php //echo $this->getReviewsSummaryHtml($_link) ?>
                        <div class="actions">
                            <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function () {
                jQuery("#owl-demo").owlCarousel({
                    navigation: true,
                    navigationText: [
                        "<i class='icon-chevron-left icon-white'></i>",
                        "<i class='icon-chevron-right icon-white'></i>"
                    ],
                    items: 5,
                    itemsDesktop: [1199, 5],
                    itemsDesktopSmall: [979, 4],
                    itemsMobile: [479, 1],
                    itemsScaleUp: false,
                    scrollPerPage: true,
                    //Pagination
                    pagination: false,
                    paginationNumbers: false,
                    autoPlay: true,
                    stopOnHover: true,
                });
            });
        </script>
    </div>
<?php endif; ?>